# Generated by Django 2.1.7 on 2019-09-04 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='id',
        ),
        migrations.AddField(
            model_name='item',
            name='x',
            field=models.AutoField(default=1, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
