# Generated by Django 2.1.7 on 2019-09-04 05:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20190904_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='x',
        ),
        migrations.AddField(
            model_name='item',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
