# Generated by Django 2.1.7 on 2019-09-04 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20190904_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
